---
- name: Clone PassMaster and set permissions
  hosts: all
  vars:
    repo_url: "https://github.com/dans6887/PassMaster.git"
    dest_path: "/home/semaphore/PassMaster" #set destionation folder to the semaphore home folder
    exec_file: "PassMaster.py"

  tasks:
    - name: Ensure git is installed #error checking to make sure git is installed
      become: true
      package:
        name: git
        state: present

    - name: Clone the PassMaster repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_path }}"
        clone: yes
        update: yes

    - name: Make the python script executable
      file:
        path: "{{ dest_path }}/{{ exec_file }}"
        mode: '0755'
